/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 51
#define YY_END_OF_BUFFER 52
static yyconst short int yy_accept[371] =
    {   0,
       35,   35,   52,   50,   51,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   37,   50,   35,   50,   50,   50,
       50,   36,   36,   36,   36,   36,   50,   36,   36,   36,
       36,   36,   36,   36,   49,    0,    0,   38,   24,    0,
        0,    0,   47,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    9,    7,    8,   37,   10,   37,   35,   13,
       21,   18,   19,    0,   36,    0,   36,   36,   36,   36,
       14,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,    0,    0,    0,   39,   48,    0,    0,    0,
        0,    0,   47,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       36,   36,   36,   36,   36,   36,    4,   36,   29,   36,
       36,   36,   36,   36,   36,   22,   23,   20,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   11,   12,   46,   45,   16,   17,   15,
        0,    0,    0,    0,    0,    0,    0,    0,   36,   36,
       36,   36,   36,   36,   28,    0,   33,    3,   36,   26,
       36,   36,   36,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   45,    0,    0,    0,    1,
        5,   36,   36,   31,   30,    0,    0,   27,   36,   25,

       36,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    2,    6,    0,    0,    0,
        0,    0,   36,   32,    0,    0,    0,    0,    0,    0,
        0,   44,    0,    0,   42,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   40,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   43,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   41,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   48,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   34,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   41,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    1,    1,    6,    1,    7,    8,
        9,   10,   11,    1,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,   16,   17,
       18,   19,    1,    1,   20,   21,   22,   20,   20,   23,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   24,   20,   20,   20,   20,   20,   20,   20,
        1,    1,    1,   25,   26,    1,   27,   20,   28,   20,

       29,   30,   31,   32,   33,   20,   20,   34,   35,   36,
       37,   38,   20,   39,   40,   41,   42,   20,   43,   20,
       20,   20,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[44] =
    {   0,
        1,    2,    3,    4,    1,    5,    1,    1,    6,    5,
        7,    7,    1,    5,    8,    9,    4,   10,    4,   11,
       11,   11,   11,   11,    1,   12,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11
    } ;

static yyconst short int yy_base[407] =
    {   0,
        0,    0, 1059, 1222, 1222, 1055, 1053, 1051, 1043,    0,
       41, 1038, 1036, 1034, 1028, 1026,   33, 1023, 1021, 1019,
     1011,   44,   46,   48,   49,   50, 1003,   54,   58,   51,
       67,   75,   76,   83, 1222,   78, 1019, 1018, 1222, 1015,
       99, 1017, 1222,  101, 1003, 1001,  999,  119,  126,   75,
       41,   57, 1222, 1003, 1001,  997,   89,  996,   98, 1222,
      992,  991,  987,  122,  124,  986,  128,  130,  131,  138,
     1222,  144,  147,  148,  150,  151,  152,  157,  158,  161,
      169,  179,  984,  981,  968, 1222, 1222,  950,  946,  942,
      932,  954, 1222,  165,  952,  176,  935,  948,  169,   83,

      166,  160,  952,  949,  947,  941,  932,  930,  928,  209,
      170,  207,  210,  211,  214,  213,  215,  223,  219,  224,
      227,  231,  232,  235,  245, 1222, 1222, 1222,  914,  898,
      897,  898,  918,  249,  914,  921,  910,  906,  190,  227,
      276,  208,  224, 1222, 1222, 1222,    0, 1222, 1222, 1222,
      300,  917,  901,  894,  891,  888,  313,  278,  264,  268,
      257,  265,  302,  304,  295,  318,  323,  326,  327,  328,
      331,  332,  334,  862,  897,  868,  864,  333,  845,  254,
      834,  245,  845,  366,  272,    0,  344,  352,  383,  335,
      336,  369,  373,  362,  370,  374,  378,  395,  396,  397,

      399,  819,  400,  810,  842,  402,  426,  828,  824,  286,
      406,  363,  824,  781,  405,  407,  408,  416,  421,  778,
      775,  430,  429,  433,  437,  774,  758,  783,  445,  447,
      485, 1222,  762,  449, 1222,  455,  454,  457,  760,  756,
      456,  478,  769,  478,  755,  752,  707,  496,  499,  718,
        0,  391,  463,  705,  468,  504,  704,  701,  506,  495,
      510, 1222,  524,  514,  518,  700,  526,  673,  530,  666,
      147,  647,  522,  540, 1222,  521,  535,  544,  537,  551,
      558,  616,  613,  592,  540,  588,  564,  550,  547,  540,
      552,  500,    0,  560,  567,  571,  577,  560,    0, 1222,

      588,  582,  505,  473,  616,  595,  598,  616,  623,  477,
      600,  461,  458,  597,  660,  433,  204,  407,  304,  582,
      633,  698,  649,  626,  358,  352,  567, 1222,  288,  262,
      617,  508,  606,  619,  631,  657,  680,  669,  673,  193,
      159,  653,  724,  256,  338,  691,   96,  764,   99,   79,
       53,  426,    0,  795,  643,  688,   46,  766,    0,  659,
      650,  772,  836,  706,  852,  775,  891,  707,  893, 1222,
      909,  914,  923,  932,  941,  948,  957,  963,  973,  985,
      995, 1005, 1014, 1023, 1033, 1042, 1052, 1061, 1071, 1075,
     1085, 1094, 1103, 1113, 1123, 1134, 1139, 1148, 1153, 1157,

     1162, 1171, 1182, 1189, 1199, 1209
    } ;

static yyconst short int yy_def[407] =
    {   0,
      370,    1,  370,  370,  370,  370,  370,  371,  370,  372,
      373,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  374,  374,  374,  374,  374,  370,  374,  374,  374,
      374,  374,  374,  374,  370,  370,  371,  371,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  375,  375,   49,
       49,   49,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  374,  370,  374,  374,  374,  374,
      370,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  376,  370,  376,   49,  370,   49,   49,

       49,   49,  370,  370,  370,  370,  370,  370,  370,  377,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  378,  370,  370,  370,   49,
      379,   49,   49,  370,  370,  370,  380,  370,  370,  370,
      377,  370,  370,  370,  370,  370,  370,  381,  374,  374,
      374,  374,  374,  374,  374,  382,  374,  374,  374,  374,
      374,  374,  374,  370,  383,  370,  370,  376,  378,  370,
      370,   49,  383,  384,   49,  380,  385,  370,  381,  374,
      374,  374,  374,  374,  374,  386,  387,  374,  374,  374,

      374,  370,  388,  370,  389,  370,  384,  370,  370,   49,
      385,  370,  370,  390,  391,  374,  374,  370,  386,  370,
      370,  392,  374,  374,  388,  370,  370,  389,  393,  370,
      370,  370,  390,  394,  370,  370,  370,  392,  370,  370,
      395,  370,  370,  393,  370,  370,  370,  370,  370,  396,
      397,  370,  370,  370,  370,  394,  370,  370,  370,  370,
      370,  370,  370,  398,  370,  370,  399,  370,  399,  396,
      396,  370,  370,  389,  370,  370,  370,  370,  370,  370,
      398,  370,  370,  370,  370,  370,  370,  400,  370,  370,
      396,  370,  274,  393,  393,  393,  393,  370,  401,  370,

      370,  399,  402,  400,  396,  393,  393,  393,  393,  370,
      370,  403,  402,  404,  396,  396,  396,  396,  396,  396,
      393,  405,  393,  393,  370,  403,  403,  370,  370,  370,
      404,  396,  396,  396,  396,  393,  406,  393,  403,  370,
      370,  396,  370,  396,  396,  406,  370,  393,  403,  370,
      370,  396,  343,  370,  396,  231,  370,  396,  354,  396,
      396,  396,  396,  396,  370,  396,  396,  396,  396,    0,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,

      370,  370,  370,  370,  370,  370
    } ;

static yyconst short int yy_nxt[1266] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,    4,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,    4,   22,   22,   28,   29,
       22,   22,   30,   22,   22,   22,   22,   31,   32,   33,
       22,   22,   34,   41,   42,   58,   64,   59,   64,   43,
       64,   64,   64,   64,  328,   44,   64,   45,   46,   47,
       64,   66,   49,   66,  357,   66,   66,   66,   66,   64,
       50,   66,   97,   51,   67,   66,  101,   64,   64,   68,
       52,   69,   72,   76,   66,   64,   77,   73,   97,  357,
       70,   74,   66,   66,   83,   84,   85,  102,  105,   75,

       66,   41,  106,  327,   42,   78,   97,   87,  100,   93,
       58,   79,   59,  356,   97,   44,   80,   45,   46,   47,
       88,   81,   42,  141,   64,   82,   64,   93,   89,   42,
       64,   90,   64,   64,   93,   45,   98,   47,   91,   66,
       64,   66,   45,   98,   47,   66,   64,   66,   66,   64,
       64,  271,   64,   64,   64,   66,  112,   99,  111,   64,
       64,   66,  291,   64,   66,   66,  113,   66,   66,   66,
      351,   64,   64,   93,   66,   66,  114,  115,   66,  134,
      119,   64,  135,  116,   93,  118,   66,   66,  117,  121,
      134,   97,  120,  138,  122,  140,   66,   97,  143,  123,

       97,  124,  159,  350,  180,  181,  142,  137,  271,   64,
      125,  151,   64,   64,  152,   64,   64,  166,  153,  154,
      155,   64,  156,  157,   66,   64,   64,   66,   66,   64,
       66,   66,   66,   64,   64,  332,   66,   64,  141,   97,
       66,   66,  161,  162,   66,  160,  163,   64,   66,   66,
      167,  165,   66,  164,  168,   97,  185,   93,   97,   64,
      271,  169,   66,  134,  171,  182,   64,   64,  180,  181,
       64,  170,  141,  341,   66,  172,   97,  173,  183,   42,
      188,   66,   66,  152,   93,   66,  343,  153,  154,  155,
       97,  156,   45,   98,   47,  191,  192,   64,  340,  190,

      193,   97,  151,   97,   64,  152,   64,  210,  271,  153,
      154,  155,   66,  156,  157,  188,  141,   97,  152,   66,
      166,   66,  153,  154,  155,   64,  156,  157,  197,   64,
       64,  194,  195,   64,   64,   66,   64,   64,  215,  334,
       66,   93,  271,   66,   66,   66,  211,  134,   66,   66,
      370,   66,   66,   66,  188,  198,  327,  152,  212,  213,
      200,  153,  154,  155,   64,  156,  199,  201,  206,   42,
      355,   64,   64,  257,   93,   64,  218,  212,  213,   66,
      197,  208,   45,  209,   47,  188,   66,   66,  152,  220,
       66,  221,  153,  154,  155,   66,  156,   64,   64,   64,

      216,   64,  206,  217,  206,  273,  208,  215,  211,   64,
       64,  271,   66,   66,   66,  208,   66,  226,  218,  226,
      212,  213,   66,  218,   66,   66,  223,  224,  206,   42,
      271,  241,  237,  221,   93,   64,  220,  271,  221,  206,
      333,  208,   45,  209,   47,  239,   66,  240,  243,  248,
       66,  255,  208,  343,  226,   87,  237,  259,  241,  237,
      313,  245,  246,  247,  257,  327,  258,  260,   88,  261,
      255,  240,  239,   66,  240,  252,   89,  253,  254,   90,
      249,  243,  250,  325,  251,  258,   91,  249,  286,  250,
      252,  251,  265,  208,  245,  246,  247,  252,  248,  253,

      254,  249,  137,  250,   87,  251,  255,  313,  259,  277,
      220,  252,  271,  265,  208,  208,  280,   88,  260,  257,
      261,  258,  260,  298,  261,   89,  278,  299,   90,  282,
      252,  283,  265,  208,  342,   91,  273,  208,  279,  239,
      285,  286,  293,  287,  285,  286,  278,  290,   87,  277,
      220,  279,  239,  280,  285,  286,  271,  302,  279,  239,
      280,  294,  298,  243,  302,  286,  299,  305,  283,  295,
      243,  327,  296,  282,  243,  283,  245,  246,  247,  297,
      243,  302,  339,  245,  246,  247,  271,  245,  246,  247,
      311,  306,  312,  245,  246,  247,  285,  286,  243,  370,

      307,  243,  311,  303,  312,  328,  308,  329,  330,  302,
      271,  245,  246,  247,  245,  246,  247,  309,  315,  243,
      271,  321,  335,  271,  316,  328,  243,  329,  330,  243,
      301,  300,  245,  246,  247,  271,  243,  317,  322,  245,
      246,  247,  245,  246,  247,  318,  343,  271,  319,  245,
      246,  247,  243,  292,  271,  320,  323,  271,  338,  344,
      243,  324,  315,  271,  271,  245,  246,  247,  316,  345,
      271,  336,  243,  245,  246,  247,  362,  327,  361,  322,
      343,  317,  206,  243,  322,  245,  246,  247,  349,  318,
      289,  352,  319,  206,  243,  208,  245,  347,  247,  320,

      183,  243,  265,  208,  348,  289,  208,  245,  347,  247,
      271,  271,  244,  271,  245,  246,  247,  284,  276,  275,
      274,  291,  271,  244,  270,  269,  353,  270,  271,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  354,  354,  354,  354,  354,  270,  270,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  243,  358,  268,
      271,  267,  266,  263,  363,  262,  364,  213,  365,  271,
      245,  246,  247,  360,  366,  228,  367,  291,  175,  369,
      291,  242,  236,  235,  322,  270,  213,  358,  270,  271,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  359,
      291,  270,  360,  270,  359,  359,  359,  359,  359,  270,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  363,  232,
      364,  231,  365,  230,  228,  227,  175,  183,  366,  205,
      367,  291,  270,   93,  270,  270,  271,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  368,  270,  270,  270,
      270,  368,  368,  368,  368,  368,  270,  270,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  271,  204,  271,  175,  183,

      202,  187,  187,  366,  187,  367,  291,  369,  291,   37,
      187,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   40,  187,  178,   40,   48,   48,  178,   48,   93,
       48,  178,   48,   48,   65,  178,  177,  176,  175,   65,
      174,   65,   65,   65,   97,  150,   97,  149,   97,  148,
       97,   97,   97,  136,  147,  136,  146,  136,  136,  158,
      145,  158,  144,  158,  158,  139,   97,  158,  179,  137,
      179,  133,  132,  179,  179,  184,  184,  131,  184,  130,
      184,  129,  184,  184,  184,  186,  128,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  189,  127,  189,

      126,  189,  189,  110,  109,  189,  189,  196,  108,  107,
       56,   56,  104,  103,  196,  196,  203,   96,   95,   94,
       92,   86,   38,   38,  203,  207,  207,   71,  207,   63,
      207,  207,  207,  207,  207,  214,   62,   61,   60,   57,
      214,  214,   56,  214,  219,   55,   54,   53,   39,  219,
      219,  219,  219,  219,  222,   38,   36,   35,  370,  370,
      370,  222,  222,  225,  370,  370,  370,  370,  225,  225,
      225,  225,  225,  229,  370,  370,  370,  370,  370,  370,
      370,  229,  233,  233,  370,  233,  233,  234,  370,  370,
      370,  370,  370,  370,  234,  234,  238,  370,  370,  370,

      370,  238,  238,  238,  238,  238,  244,  370,  370,  370,
      244,  370,  244,  244,  244,  256,  370,  370,  370,  370,
      256,  256,  256,  256,  256,  264,  370,  370,  370,  370,
      370,  370,  264,  264,  270,  370,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  272,  370,  370,  272,
      281,  370,  370,  370,  370,  281,  281,  281,  281,  281,
      288,  288,  288,  288,  304,  304,  370,  304,  304,  310,
      370,  370,  310,  314,  370,  370,  370,  370,  370,  370,
      370,  314,  326,  370,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  331,  331,  331,  370,  370,  331,

      331,  337,  337,  370,  370,  370,  337,  370,  337,  337,
      337,  346,  346,  370,  370,  370,  346,  346,  346,  346,
      346,    3,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370
    } ;

static yyconst short int yy_chk[1266] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   11,   11,   17,   22,   17,   23,   11,
       24,   25,   26,   30,  357,   11,   28,   11,   11,   11,
       29,   22,   11,   23,  351,   24,   25,   26,   30,   31,
       11,   28,   51,   11,   23,   29,   51,   32,   33,   24,
       11,   25,   28,   30,   31,   34,   30,   29,   52,  350,
       26,   29,   32,   33,   36,   36,   36,   52,   57,   29,

       34,   41,   57,  349,   44,   31,   50,   41,   50,   44,
       59,   32,   59,  347,  100,   44,   33,   44,   44,   44,
       41,   34,   48,  100,   64,   34,   65,   48,   41,   49,
       67,   41,   68,   69,   49,   48,   48,   48,   41,   64,
       70,   65,   49,   49,   49,   67,   72,   68,   69,   73,
       74,  271,   75,   76,   77,   70,   68,   49,   67,   78,
       79,   72,  271,   80,   73,   74,   69,   75,   76,   77,
      341,   81,  111,   94,   78,   79,   70,   72,   80,   94,
       76,   82,   94,   73,   96,   75,   81,  111,   74,   78,
       96,  102,   77,   96,   79,   99,   82,  101,  102,   80,

       99,   81,  111,  340,  139,  139,  101,  139,  317,  112,
       82,  110,  113,  114,  110,  116,  115,  117,  110,  110,
      110,  119,  110,  110,  112,  118,  120,  113,  114,  121,
      116,  115,  117,  122,  123,  317,  119,  124,  142,  142,
      118,  120,  113,  114,  121,  112,  115,  125,  122,  123,
      118,  116,  124,  115,  120,  143,  143,  134,  140,  161,
      344,  121,  125,  134,  123,  140,  159,  162,  180,  180,
      160,  122,  182,  330,  161,  124,  182,  125,  141,  141,
      158,  159,  162,  158,  141,  160,  344,  158,  158,  158,
      141,  158,  141,  141,  141,  160,  161,  165,  329,  159,

      162,  141,  151,  185,  163,  151,  164,  185,  319,  151,
      151,  151,  165,  151,  151,  157,  210,  210,  157,  163,
      166,  164,  157,  157,  157,  167,  157,  157,  168,  169,
      170,  163,  164,  171,  172,  166,  173,  190,  191,  319,
      167,  178,  345,  168,  169,  170,  187,  178,  171,  172,
      178,  173,  190,  191,  188,  169,  326,  188,  187,  187,
      172,  188,  188,  188,  194,  188,  171,  173,  184,  184,
      345,  192,  195,  325,  184,  193,  196,  212,  212,  194,
      197,  184,  184,  184,  184,  189,  192,  195,  189,  196,
      193,  196,  189,  189,  189,  197,  189,  198,  199,  200,

      192,  201,  203,  193,  206,  252,  252,  215,  211,  216,
      217,  318,  198,  199,  200,  203,  201,  203,  218,  206,
      211,  211,  215,  219,  216,  217,  199,  201,  207,  207,
      352,  223,  222,  218,  207,  224,  219,  316,  219,  225,
      318,  207,  207,  207,  207,  222,  223,  222,  229,  230,
      224,  234,  225,  352,  225,  230,  237,  236,  241,  238,
      313,  229,  229,  229,  234,  312,  234,  236,  230,  236,
      255,  237,  238,  241,  238,  253,  230,  253,  253,  230,
      242,  244,  242,  310,  242,  255,  230,  231,  304,  231,
      242,  231,  242,  242,  244,  244,  244,  231,  248,  231,

      231,  249,  231,  249,  248,  249,  256,  303,  259,  260,
      260,  249,  332,  249,  249,  292,  264,  248,  259,  256,
      259,  256,  261,  276,  261,  248,  263,  276,  248,  264,
      265,  264,  265,  265,  332,  248,  273,  273,  263,  263,
      267,  267,  274,  267,  269,  269,  278,  269,  274,  277,
      277,  279,  279,  280,  285,  285,  291,  290,  278,  278,
      281,  274,  298,  294,  289,  288,  298,  291,  280,  274,
      295,  327,  274,  281,  296,  281,  294,  294,  294,  274,
      297,  287,  327,  295,  295,  295,  320,  296,  296,  296,
      301,  294,  301,  297,  297,  297,  302,  302,  306,  302,

      295,  307,  311,  286,  311,  314,  296,  314,  314,  284,
      333,  306,  306,  306,  307,  307,  307,  297,  305,  308,
      305,  306,  320,  334,  305,  331,  309,  331,  331,  324,
      283,  282,  308,  308,  308,  335,  321,  305,  307,  309,
      309,  309,  324,  324,  324,  305,  333,  355,  305,  321,
      321,  321,  323,  272,  361,  305,  308,  342,  324,  334,
      336,  309,  315,  360,  315,  323,  323,  323,  315,  335,
      270,  321,  338,  336,  336,  336,  360,  339,  355,  323,
      361,  315,  337,  337,  336,  338,  338,  338,  339,  315,
      268,  342,  315,  346,  346,  337,  337,  337,  337,  315,

      322,  322,  356,  356,  338,  356,  346,  346,  346,  346,
      364,  368,  322,  368,  322,  322,  322,  266,  258,  257,
      254,  364,  250,  322,  343,  247,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  348,  358,  246,
      358,  245,  243,  240,  362,  239,  362,  233,  362,  366,
      348,  348,  348,  358,  362,  228,  362,  362,  227,  366,
      366,  226,  221,  220,  348,  354,  214,  354,  354,  354,

      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  363,  213,
      363,  209,  363,  208,  205,  204,  202,  183,  363,  181,
      363,  363,  365,  179,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  367,  177,  369,  176,  175,

      174,  156,  155,  367,  154,  367,  367,  369,  369,  371,
      153,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  372,  152,  138,  372,  373,  373,  137,  373,  136,
      373,  135,  373,  373,  374,  133,  132,  131,  130,  374,
      129,  374,  374,  374,  375,  109,  375,  108,  375,  107,
      375,  375,  375,  376,  106,  376,  105,  376,  376,  377,
      104,  377,  103,  377,  377,   98,   97,  377,  378,   95,
      378,   92,   91,  378,  378,  379,  379,   90,  379,   89,
      379,   88,  379,  379,  379,  380,   85,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  381,   84,  381,

       83,  381,  381,   66,   63,  381,  381,  382,   62,   61,
       58,   56,   55,   54,  382,  382,  383,   47,   46,   45,
       42,   40,   38,   37,  383,  384,  384,   27,  384,   21,
      384,  384,  384,  384,  384,  385,   20,   19,   18,   16,
      385,  385,   15,  385,  386,   14,   13,   12,    9,  386,
      386,  386,  386,  386,  387,    8,    7,    6,    3,    0,
        0,  387,  387,  388,    0,    0,    0,    0,  388,  388,
      388,  388,  388,  389,    0,    0,    0,    0,    0,    0,
        0,  389,  390,  390,    0,  390,  390,  391,    0,    0,
        0,    0,    0,    0,  391,  391,  392,    0,    0,    0,

        0,  392,  392,  392,  392,  392,  393,    0,    0,    0,
      393,    0,  393,  393,  393,  394,    0,    0,    0,    0,
      394,  394,  394,  394,  394,  395,    0,    0,    0,    0,
        0,    0,  395,  395,  396,    0,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  397,    0,    0,  397,
      398,    0,    0,    0,    0,  398,  398,  398,  398,  398,
      399,  399,  399,  399,  400,  400,    0,  400,  400,  401,
        0,    0,  401,  402,    0,    0,    0,    0,    0,    0,
        0,  402,  403,    0,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  404,  404,  404,    0,    0,  404,

      404,  405,  405,    0,    0,    0,  405,    0,  405,  405,
      405,  406,  406,    0,    0,    0,  406,  406,  406,  406,
      406,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "main.l"
#define INITIAL 0
#line 2 "main.l"

  extern FILE *yyin;
  
  extern FILE *yyout;

#line 776 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 28 "main.l"




#line 932 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 371 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1222 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 32 "main.l"
{printf("Start_of_Program ");}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 33 "main.l"
{printf("End_of_Program ");}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 34 "main.l"
{printf("Integer_type ");}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 35 "main.l"
{printf("Float_type ");}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 36 "main.l"
{printf("Character_type ");}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 37 "main.l"
{printf("String_type ");}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 38 "main.l"
{printf("Add ");}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 39 "main.l"
{printf("Substruct ");}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 40 "main.l"
{printf("Multiply ");}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 41 "main.l"
{printf("Divide ");}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 42 "main.l"
{printf("Increment");}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 43 "main.l"
{{printf("Decrement");}}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 44 "main.l"
{printf("End_of_Line ");}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 45 "main.l"
{printf("Exponent ");}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 46 "main.l"
{printf("Greater_than_or_equal ");}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 47 "main.l"
{printf("Less_than_or_equal ");}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 48 "main.l"
{printf("Equal ");}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 49 "main.l"
{printf("Asign ");}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 50 "main.l"
{printf("Greater_than ");}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 51 "main.l"
{printf("Not_greater_than ");}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 52 "main.l"
{printf("Less_than ");}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 53 "main.l"
{printf("Not_less_than ");}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 54 "main.l"
{printf("Not_Equal ");}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 55 "main.l"
{printf("Remainder ");}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 56 "main.l"
{printf("Print ");}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 57 "main.l"
{printf("Root ");}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 58 "main.l"
{printf("Prime ");}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "main.l"
{printf("For_loop");}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "main.l"
{printf("If_Condition");}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 61 "main.l"
{printf("Else_Condition");}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 62 "main.l"
{printf("Elseif_Condition");}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 63 "main.l"
{printf("While_Condition");}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 64 "main.l"
{printf("User_defined_function ");}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 66 "main.l"
{printf("( initializationStatement; testExpression; updateStatement )");}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 69 "main.l"
{printf("Integer ");}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 70 "main.l"
{printf("Variable ");}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 71 "main.l"
{printf("Float ");}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 72 "main.l"
{printf("String ");} 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 73 "main.l"
{printf("Character ");}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 75 "main.l"
{printf("Integer_type_variable Declared: %s\n ",yytext);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 76 "main.l"
{printf("String_type_variable Declared: %s\n ",yytext);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 77 "main.l"
{printf("Float_type_variable Declared: %s\n ",yytext);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 78 "main.l"
{printf("Character_type_variable Declared: %s\n ",yytext);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 80 "main.l"
{printf(" %s\n ",yytext);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 82 "main.l"
{printf("Single Line Comment");}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 84 "main.l"
{
    printf("Multiple_Line_Comment_Starts\n");
    char c;
    label:
        while(c = input() != '*');
    if(c = input() == '*') {
    if(c = input() == '/') {
      if(c = input() == '/') {
        printf("    Multiple_Line_Comment_Ends.\n");}
    }}
    else {
        goto label;
    }
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 99 "main.l"
{printf(" (Condition)\n");}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 101 "main.l"
{printf("(Function Condition: %s)",yytext);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 103 "main.l"
{}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 105 "main.l"
{}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 107 "main.l"
ECHO;
	YY_BREAK
#line 1283 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 371 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 371 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 370);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 107 "main.l"

int yywrap()
{
return 1;
}
int main()
{
yyin = freopen("input.txt","r",stdin);
yyout = freopen("output.txt","w",stdout);
yylex();
return 0;
}